import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm";

const c=window.WEDDING_CONFIG,$=s=>document.querySelector(s),supabase=createClient(c.supabaseUrl,c.supabasePublishableKey);
function setMessage(t,type=""){const e=$("#adminMessage");e.textContent=t||"";e.dataset.type=type}
function fmtDate(v){return v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—"}
function fmtMoney(v,currency="BRL"){return v==null?"—":new Intl.NumberFormat("pt-BR",{style:"currency",currency:currency||"BRL"}).format(Number(v))}
function giftStatusLabel(s){return({available:"Disponível",reserved:"Reservado",purchased:"Presenteado",completed:"Presenteado"})[s]||s||"—"}
async function isAdmin(){const{data:a}=await supabase.auth.getUser();const u=a?.user;if(!u)return false;const{data}=await supabase.from("wedding_admins").select("user_id").eq("user_id",u.id).maybeSingle();return!!data}
async function adminRpc(name,params={}){const{data,error}=await supabase.rpc(name,params);if(error)throw error;return data}
async function updateUI(){const{data}=await supabase.auth.getSession(),session=data.session,admin=session?await isAdmin():false;$("#loginCard").classList.toggle("hidden",!!session&&admin);$("#adminArea").classList.toggle("hidden",!(session&&admin));if(session&&admin){$("#loggedEmail").textContent=session.user.email||"Administrador";$("#loginMessage").textContent="";await refreshAll()}else if(session&&!admin){$("#loginMessage").textContent="Esta conta não está autorizada como administradora.";await supabase.auth.signOut()}}
$("#loginBtn").addEventListener("click",async()=>{$("#loginMessage").textContent="Entrando...";const{error}=await supabase.auth.signInWithPassword({email:$("#email").value.trim(),password:$("#password").value});if(error){$("#loginMessage").textContent=error.message;return}await updateUI()});
$("#password").addEventListener("keydown",e=>{if(e.key==="Enter")$("#loginBtn").click()});
$("#logoutBtn").addEventListener("click",async()=>{await supabase.auth.signOut();await updateUI()});
async function loadGuests(){const w=$("#adminGuests");w.innerHTML='<p class="admin-empty">Carregando...</p>';try{const data=await adminRpc("wedding_admin_list_guests");$("#guestCount").textContent=data?.length||0;w.innerHTML="";if(!data?.length){w.innerHTML='<p class="admin-empty">Nenhum convidado confirmado.</p>';return}for(const g of data){const item=document.createElement("article");item.className="admin-list-item";const info=document.createElement("div");info.className="admin-list-info";const title=document.createElement("strong");title.textContent=g.name;const meta=document.createElement("span");meta.textContent=`Senha ${g.number} • ${g.phone||"sem telefone"} • ${fmtDate(g.confirmed_at)}`;info.append(title,meta);const b=document.createElement("button");b.className="admin-small-btn danger-outline";b.textContent="Excluir";b.addEventListener("click",async()=>{if(!confirm(`Excluir ${g.name} da lista de convidados?`))return;b.disabled=true;try{await adminRpc("wedding_admin_delete_guest",{p_guest_id:g.id});setMessage("Convidado excluído.","success");await Promise.all([loadGuests(),loadGiftsAdmin()])}catch(e){setMessage(e.message,"error");b.disabled=false}});item.append(info,b);w.appendChild(item)}}catch(e){w.innerHTML='<p class="admin-empty">Não foi possível carregar os convidados.</p>';setMessage(e.message,"error")}}
async function loadGiftsAdmin(){const w=$("#adminGifts");w.innerHTML='<p class="admin-empty">Carregando...</p>';try{const data=await adminRpc("wedding_admin_list_gifts");$("#giftCount").textContent=data?.length||0;w.innerHTML="";if(!data?.length){w.innerHTML='<p class="admin-empty">Nenhum presente cadastrado.</p>';return}for(const g of data){const item=document.createElement("article");item.className="admin-list-item";const info=document.createElement("div");info.className="admin-list-info";const title=document.createElement("strong");title.textContent=g.title;const meta=document.createElement("span");meta.textContent=`${giftStatusLabel(g.status)} • ${fmtMoney(g.current_price,g.currency)}`;info.append(title,meta);const b=document.createElement("button");b.className="admin-small-btn";b.textContent="Disponível novamente";b.disabled=g.status==="available"&&g.is_active;b.addEventListener("click",async()=>{if(!confirm(`Tornar \"${g.title}\" disponível novamente?`))return;b.disabled=true;try{await adminRpc("wedding_admin_reset_gift",{p_gift_id:g.id});setMessage("Presente liberado novamente.","success");await loadGiftsAdmin()}catch(e){setMessage(e.message,"error");b.disabled=false}});item.append(info,b);w.appendChild(item)}}catch(e){w.innerHTML='<p class="admin-empty">Não foi possível carregar os presentes.</p>';setMessage(e.message,"error")}}
async function loadPhotos(){const{data,error}=await supabase.from("wedding_photos").select("id,storage_path,alt_text,is_active,position,created_at").order("position").order("created_at");if(error){setMessage(error.message,"error");return}$("#photoCount").textContent=data?.length||0;const w=$("#adminPhotos");w.innerHTML="";if(!data?.length){w.innerHTML='<p class="admin-empty">Nenhuma foto enviada.</p>';return}for(const row of data){const{data:url}=supabase.storage.from("wedding-photos").getPublicUrl(row.storage_path);const item=document.createElement("article");item.className="admin-photo-item";const img=document.createElement("img");img.src=url.publicUrl;img.alt=row.alt_text||"Foto do casal";const box=document.createElement("div"),p=document.createElement("p");p.textContent=row.alt_text||"Sem legenda";const b=document.createElement("button");b.className="admin-small-btn danger-outline";b.textContent="Remover";b.addEventListener("click",async()=>{if(!confirm("Remover esta foto do carrossel?"))return;const{error:s}=await supabase.storage.from("wedding-photos").remove([row.storage_path]);if(s){setMessage(s.message,"error");return}const{error:d}=await supabase.from("wedding_photos").delete().eq("id",row.id);if(d){setMessage(d.message,"error");return}setMessage("Foto removida.","success");await loadPhotos()});box.append(p,b);item.append(img,box);w.appendChild(item)}}
$("#uploadBtn").addEventListener("click",async()=>{const files=Array.from($("#photoFiles").files||[]);if(!files.length){setMessage("Escolha pelo menos uma foto.","error");return}if(!(await isAdmin())){setMessage("Sessão sem permissão administrativa.","error");return}setMessage("Enviando fotos...");const alt=$("#photoAlt").value.trim();for(const file of files){if(file.size>8*1024*1024){setMessage(`${file.name} excede 8 MB.`,"error");return}const ext=(file.name.split(".").pop()||"jpg").toLowerCase(),path=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const{error:u}=await supabase.storage.from("wedding-photos").upload(path,file,{cacheControl:"3600",upsert:false});if(u){setMessage(u.message,"error");return}const{error:i}=await supabase.from("wedding_photos").insert({storage_path:path,alt_text:alt||null,is_active:true});if(i){await supabase.storage.from("wedding-photos").remove([path]);setMessage(i.message,"error");return}}$("#photoFiles").value="";$("#photoAlt").value="";setMessage("Fotos adicionadas com sucesso.","success");await loadPhotos()});
async function removeAllPhotos(){const{data,error}=await supabase.from("wedding_photos").select("id,storage_path");if(error)throw error;const paths=(data||[]).map(x=>x.storage_path).filter(Boolean);if(paths.length){const{error:e}=await supabase.storage.from("wedding-photos").remove(paths);if(e)throw e}if(data?.length){const{error:e}=await supabase.from("wedding_photos").delete().in("id",data.map(x=>x.id));if(e)throw e}}
$("#resetConfirmText").addEventListener("input",()=>{$("#resetSiteBtn").disabled=$("#resetConfirmText").value.trim().toUpperCase()!=="LIMPAR"});
$("#resetSiteBtn").addEventListener("click",async()=>{if($("#resetConfirmText").value.trim().toUpperCase()!=="LIMPAR")return;if(!confirm("ATENÇÃO: isso excluirá todos os convidados, todas as fotos e todos os registros de presentes/reservas. Os presentes cadastrados voltarão a ficar disponíveis. Deseja continuar?"))return;const b=$("#resetSiteBtn");b.disabled=true;setMessage("Limpando os dados do site...");try{await removeAllPhotos();await adminRpc("wedding_admin_reset_site_data");$("#resetConfirmText").value="";setMessage("Site limpo com sucesso.","success");await refreshAll()}catch(e){setMessage(`A limpeza não foi concluída: ${e.message}`,"error")}finally{b.disabled=$("#resetConfirmText").value.trim().toUpperCase()!=="LIMPAR"}});
$("#refreshGuestsBtn").addEventListener("click",loadGuests);$("#refreshGiftsBtn").addEventListener("click",loadGiftsAdmin);
async function refreshAll(){setMessage("");await Promise.all([loadGuests(),loadGiftsAdmin(),loadPhotos()])}
supabase.auth.onAuthStateChange(()=>setTimeout(updateUI,0));await updateUI();
